CREATE TABLE `applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`propertyId` int NOT NULL,
	`userId` int,
	`status` enum('pending','under_review','approved','denied','incomplete') NOT NULL DEFAULT 'pending',
	`fullName` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50) NOT NULL,
	`dateOfBirth` varchar(20),
	`ssnLast4` varchar(4),
	`currentAddress` text,
	`moveInDate` varchar(20),
	`moveOutDate` varchar(20),
	`reasonForLeaving` text,
	`previousLandlordName` varchar(255),
	`previousLandlordPhone` varchar(50),
	`employerName` varchar(255),
	`position` varchar(255),
	`monthlyIncome` int,
	`supervisorContact` varchar(255),
	`additionalOccupants` text,
	`pets` text,
	`vehicles` text,
	`emergencyContactName` varchar(255),
	`emergencyContactPhone` varchar(50),
	`consentGiven` boolean NOT NULL DEFAULT false,
	`signatureData` text,
	`signatureDate` timestamp,
	`idDocumentUrl` varchar(500),
	`incomeProofUrl` varchar(500),
	`applicationFeePaid` boolean NOT NULL DEFAULT false,
	`applicationFeeAmount` int,
	`paymentTransactionId` varchar(255),
	`adminNotes` text,
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `applications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `leases` (
	`id` int AUTO_INCREMENT NOT NULL,
	`propertyId` int NOT NULL,
	`tenantId` int NOT NULL,
	`applicationId` int,
	`leaseStartDate` timestamp NOT NULL,
	`leaseEndDate` timestamp NOT NULL,
	`monthlyRent` int NOT NULL,
	`securityDeposit` int NOT NULL,
	`leaseDocumentUrl` varchar(500),
	`status` enum('active','expired','terminated','pending') NOT NULL DEFAULT 'pending',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leases_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `maintenanceRequests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`propertyId` int NOT NULL,
	`tenantId` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text NOT NULL,
	`urgency` enum('low','medium','high','emergency') NOT NULL DEFAULT 'medium',
	`status` enum('open','in_progress','completed','cancelled') NOT NULL DEFAULT 'open',
	`images` text,
	`assignedTo` int,
	`completedAt` timestamp,
	`adminNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `maintenanceRequests_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `messages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`senderId` int NOT NULL,
	`recipientId` int,
	`propertyId` int,
	`subject` varchar(255),
	`content` text NOT NULL,
	`isRead` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `messages_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `payments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`leaseId` int NOT NULL,
	`tenantId` int NOT NULL,
	`amount` int NOT NULL,
	`paymentType` enum('rent','deposit','fee','other') NOT NULL,
	`paymentMethod` varchar(50),
	`transactionId` varchar(255),
	`status` enum('pending','completed','failed','refunded') NOT NULL DEFAULT 'pending',
	`paymentDate` timestamp NOT NULL,
	`dueDate` timestamp,
	`notes` text,
	`receiptUrl` varchar(500),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `payments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `properties` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`address` text NOT NULL,
	`city` varchar(100) NOT NULL,
	`state` varchar(50) NOT NULL,
	`zipCode` varchar(20) NOT NULL,
	`propertyType` varchar(50) NOT NULL,
	`bedrooms` int NOT NULL,
	`bathrooms` int NOT NULL,
	`squareFeet` int,
	`rentAmount` int NOT NULL,
	`depositAmount` int NOT NULL,
	`isAvailable` boolean NOT NULL DEFAULT false,
	`availableDate` timestamp,
	`description` text,
	`amenities` text,
	`petsAllowed` boolean NOT NULL DEFAULT false,
	`utilitiesIncluded` text,
	`images` text,
	`floorPlanUrl` varchar(500),
	`virtualTourUrl` varchar(500),
	`latitude` varchar(50),
	`longitude` varchar(50),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `properties_id` PRIMARY KEY(`id`)
);
